### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Miltage** [patrickschur/pappet#1]
```
pappet -s https://youtube.com
https://youtube.com
(node:5866) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at urlToPath (/usr/local/lib/node_modules/pappet/index.js:191:28)
    at openTab (/usr/local/lib/node_modules/pappet/index.js:235:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what's going wrong here?

**Comment by patrickschur** [comment]
I have no idea, it works fine for me. Which node version have you used?

**Comment by Miltage** [comment]
6.9.0

Running on macOS High Sierra Version 10.13.6 (17G4015)

**Comment by patrickschur** [comment]
Thanks, I've tested pappet with node version 6.9.5 on my local machine and it looks like the version doesn't support some of the newer ES6 features that are used by pappet.

Because the installed node version is a bit outdated, I would recommend you to update to a newer node version (10 or higher).

**Comment by Miltage** [comment]
I've upgraded and it works! Sorry for the trouble.
