### ISSUE TITLE
Unsupported screenshot mime type: null

### ISSUE THREAD

**Issue by camjc** [patrickschur/pappet#2]
Thanks for a great tool!

Hit an error throwing inside puppeteer and not sure if its something in this repo or theirs thats the cause, maybe you can illuminate me.

```
(node:55221) UnhandledPromiseRejectionWarning: Error: Unsupported screenshot mime type: null
    at assert (/usr/local/lib/node_modules/pappet/node_modules/puppeteer/lib/helper.js:267:11)
    at Page.screenshot (/usr/local/lib/node_modules/pappet/node_modules/puppeteer/lib/Page.js:818:7)
    at Page.<anonymous> (/usr/local/lib/node_modules/pappet/node_modules/puppeteer/lib/helper.js:112:23)
    at openTab (/usr/local/lib/node_modules/pappet/index.js:238:28)
    at async Promise.all (index 1)
    at async openBrowser (/usr/local/lib/node_modules/pappet/index.js:267:5)
    at async Promise.all (index 0)
    at async /usr/local/lib/node_modules/pappet/index.js:278:5
```

occurred using command `pappet --screenshot --recursive --is-mobile -w 375 -h 667 --same-origin --full-page --level 1000 --tabs 8 https://www.frank.com.au`

**Comment by patrickschur** [comment]
Hello,

this is indeed an issue inside [puppeteer](https://github.com/GoogleChrome/puppeteer/issues/4395). For some reason puppeteer detects the mime type from the path, which is more than bad.

But I'm able to fix the issue. :)

I also found another issue, where the screenshot is not correctly cropped. Are you sure you want to crop the screenshot to a size of 375x667px? Because this will result in something like this after the patch.

![image](https://user-images.githubusercontent.com/18181635/60742503-ea242600-9f6d-11e9-8b76-368bb8cb3151.png)

**Comment by camjc** [comment]
@patrickschur This is just an example website, looks like they're not responsive in regular browsers either so not a puppeteer/pappet issue at all.

Awesome you could figure out how to work around it. Thanks heaps!
- Cam
